name: polkadot
base: core22
version: "0.1"

summary: Polkadot - A multi-chain framework for better blockchain interoperability
description: |
  Polkadot is a multi-chain framework that enables interoperability and scalability for multiple blockchains.

grade: stable
confinement: strict

parts:
  polkadot:
    plugin: rust
    source: https://github.com/paritytech/polkadot.git
    source-tag: v0.9.42
    # rustup-channel: stable
    # rustup-targets:
    #  - wasm32-unknown-unknown
    # rust-features:
    #  - wasm-pack:0.11.1
    source-depth: 1
    build-environment:
      - RUSTUP_TOOLCHAIN: stable
      - RUSTUP_TARGET: wasm32-unknown-unknown
      - CARGO_PROFILE_RELEASE_BUILD_OVERRIDE: "--release"
    build-packages:
      - curl
      - build-essential
      - libssl-dev
      - git 
      - clang 
      - libclang-dev 
      - pkg-config
      - protobuf-compiler 
    build-snaps:
      - rustup
    after: [install-wasm-toolchain]

  install-wasm-toolchain:
    plugin: nil
    override-build: |
      rustup default stable
      rustup target add wasm32-unknown-unknown
      rustup update
      cargo install wasm-pack --version 0.11.1
    


  wrappers:
    plugin: dump
    source-type: local
    source: .
    stage:
      - wrappers/

  files:
    plugin: dump
    source-type: local
    source: ./files
    organize:
      service-arguments: etc/service-arguments

apps:
  polkadot:
    command: wrappers/start-polkadot.sh $SNAP_DATA/service-arguments
    daemon: simple
    install-mode: disable
    refresh-mode: endure
    restart-condition: never
    plugs:
      - network
      - network-bind
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

plugs:
  network:
  network-bind:

