name: polkadot
base: core22
adopt-info: polkadot
summary: Polkadot - A multi-chain framework for better blockchain interoperability
contact: polkadot-devel@dwellir.com
issues: https://github.com/dwellir-public/snap-polkadot/issues
source-code: https://github.com/dwellir-public/snap-polkadot/
website: https://www.dwellir.com
grade: stable
confinement: strict

architectures:
  - amd64
  - arm64

description: |
  Polkadot is a multi-chain framework that enables interoperability and scalability for multiple blockchains.
  See: https://github.com/paritytech/polkadot-sdk

  Maintained by Dwellir https://www.dwellir.com

  Supported configuration options for the snap:
  
  service-args [default=--base-path=$SNAP_COMMON/polkadot_base --name=<hostname>]
  For available arguments see https://github.com/paritytech/polkadot-sdk
  The value set here will be passed to the Polkadot binary with a few exceptions listed below. 
  * --name defaults to the systems hostname the first time the snap is installed.
  * --base-path is always set by the snap to `$SNAP_COMMON/polkadot_base` and is not allowed to be configured.

  Start the service with 'sudo snap start polkadot'

  Check logs from the Polkadot service with 'snap logs polkadot -f'

parts:

  rust-deps:
    plugin: nil
    build-packages:
     - curl
    override-pull: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source "$HOME/.cargo/env"
      rustup target add wasm32-unknown-unknown

  polkadot:
    after: [rust-deps]
    plugin: rust
    source: https://github.com/paritytech/polkadot-sdk.git
    source-tag: polkadot-v1.1.0
    source-depth: 1
    build-packages:
      - build-essential
      - libssl-dev
      - git 
      - clang 
      - libclang-dev 
      - pkg-config
      - protobuf-compiler
    # Make the commit hash available for snap info
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags --abbrev=10)-$(git rev-parse --short HEAD)"
    rust-path:
      - polkadot/
    override-build: |
      ./polkadot/scripts/init.sh
      # Build main binary(s) using default function of plugin (like calling super)
      craftctl default
    prime:
      - bin/polkadot
      - bin/polkadot-execute-worker
      - bin/polkadot-prepare-worker

  wrappers:
    plugin: dump
    source-type: local
    source: .
    stage:
      - wrappers/
  
  utils:
      plugin: dump
      source-type: local
      source: .
      stage:
        - utils/

apps:
  polkadot:
    command: wrappers/start-polkadot.bash
    daemon: simple
    install-mode: disable
    refresh-mode: endure
    restart-condition: never
    plugs:
      - network
      - network-bind
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
