name: Build and publish Polkadot snap

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Clean
      run: sudo snapcraft clean
      run: sudo rm -r parts
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install snapcraft
      uses: samuelmeuli/action-snapcraft@v2
    - name: Build snap
      id: snapcraft
      run: sudo snapcraft pack --destructive-mode --verbosity debug --debug
    - uses: actions/upload-artifact@v3
      with:
        name: polkadot-snap.snap
        path: polkadot_*_amd64.snap
    - name: Save snapcraft log
      uses: actions/upload-artifact@v3
      if: ${{ failure() && steps.snapcraft.conclusion == 'failure' }}
      with:
        name: snapcraft.log
        path: /home/runner/.local/state/snapcraft/log/snapcraft-*.log
  # test:
  #   runs-on: ubuntu-latest
  # publish:
  #   runs-on: ubuntu-latest
