name: Build and publish Polkadot snap

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install snapcraft
      uses: samuelmeuli/action-snapcraft@v2
    - name: Clean
      run: snapcraft clean
    - name: Build snap
      id: snapcraft
      run: snapcraft pack --destructive-mode
    # - uses: snapcore/action-build@v1
    #   id: snapcraft
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: snap
    #     path: ${{ steps.snapcraft.outputs.snap }}
    # - name: Save snapcraft log
    #   uses: actions/upload-artifact@v3
    #   if: ${{ failure() && steps.snapcraft.conclusion == 'failure' }}
    #   with:
    #     name: log
    #     path: /home/runner/.local/state/snapcraft/log/snapcraft-*.log
  # test:
  #   runs-on: ubuntu-latest
  # publish:
  #   runs-on: ubuntu-latest
